---
LedgerAmounts:
  source: ledger/account-balances
  fields:
    AccountCode: AccountCode
    Balance: ClosingBalance
LedgerDetails:
  source: ledger/account-details
  fields:
    AccountName: Name
    