---
AssetsFixedAssetSummaryData:
  source: assets/fixed_asset_summary_basic
  fields:
    Sequence: Sequence
    AssetClassDescription: AssetClassDescription
    AssetAccountCode: AssetAccountCode
    AssetCostValue: AssetCostValue
    AccumulatedDepreciationAccountCode: AccumulatedDepreciationAccountCode
    AccumulatedDepreciationValue: AccumulatedDepreciationValue
    WrittenDownValue: WrittenDownValue

DepreciationExpense:
  source: assets/fixed_asset_summary_depreciation_expense
  fields:
    Sequence2: Sequence
    AssetClassDescription2: AssetClassDescription
    DepreciationExpenseAccountCode: DepreciationExpenseAccountCode
    DepreciationExpenseValue: DepreciationExpenseValue

ProfitAndLossOnSale:
  source: assets/fixed_asset_summary_profit_loss
  fields:
    AssetClassId: AssetClassId
    AssetClassCode: AssetClassCode
    AssetClassDescription3: AssetClassDescription
    Type: Type
    ProfitOrLossAccountId: ProfitOrLossAccountId
    ProfitOrLossBalance: ProfitOrLossBalance

# DepreciationMethod: assets/fixed_asset_summary_depreciation_method
# AccountingDepreciationValue: assets/fixed_asset_summary_tax_reconciliation_adjustment/AccountingDepreciationValue
# TaxDepreciationValue: assets/fixed_asset_summary_tax_reconciliation_adjustment/TaxDepreciationValue
# AccountingProfitOnSaleValue: assetModule/AccountingProfitOnSaleValue
# AccountingLossOnSale: assetModule/AccountingLossOnSale
# TaxProfitOnSaleValue: assets/fixed_asset_summary_tax_reconciliation_adjustment/TaxProfitOnSaleValue
# TaxLossOnSaleValue: assets/fixed_asset_summary_tax_reconciliation_adjustment/TaxLossOnSaleValue

LedgerAmounts:
  source: ledger/account-balances
  fields:
    AccountCode: AccountCode
    Balance: ClosingBalance
    AccountName: AccountName
